drop table if exists member CASCADE;
    create table member
    (
        id   bigint generated by default as identity,
        name varchar(255),
        primary key (id)
);


drop table if exists tag CASCADE;
    create table tag
    (
        tagKey   bigint generated by default as identity,
        tagName varchar(255),
        tagDate varchar(6),
        primary key (id)
);